ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

# Enable all available rules by default
enableAllRules = true

# Rules configuration
[rule.add-constant]
arguments = [
  { maxLitCount = "3", allowStrs = "\"\"", allowInts = "0" },
]
# Tests often contain magic numbers.
Exclude = ["TEST"]  # Same as "**/*_test.go"

[rule.line-length-limit]
arguments = [150]

[rule.max-public-structs]
arguments = [8]


# Disable specific rules
[rule.exported]
Disabled = true

[rule.package-comments]
Disabled = true
